github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

jetbrains:
  intellij:
    prebuilds:
      version: stable
