github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true

image:
  file: .gitpod.Dockerfile

jetbrains:
  intellij:
    prebuilds:
      version: stable

tasks:
  - init: ./gradlew assemble
    command: |
      echo 'TODO: start app'